"""empty message

Revision ID: 82de778736f3
Revises: 0763d677d453
Create Date: 2025-05-18 03:00:30.285869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82de778736f3'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.String(length=240), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    # ### end Alembic commands ###
